### ISSUE TITLE
Might it be better to have a seperate print with newline command for golfing purposes?

### ISSUE THREAD

**Issue by qaziquza** [FabricioLince/BehaviourEsolang#1]

**Comment by FabricioLince** [comment]
Maybe, even though golfing is not my main objective with this language.

**Comment by FabricioLince** [comment]
Went back and realized I hardly ever used the 'print without newline' command and removed it altogether. Now the single at symbol `@` prints with newline and flushes the stream. In the future, if demand arises, I can create another command to print without newline. For now, the output stream and newline or no newline is to be configurable from the host program.
